# Generated by Django 5.2.7 on 2025-12-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('creation_bon', 'Création de bon'), ('verification_cotisation', 'Vérification de cotisation'), ('consultation_membre', 'Consultation de membre'), ('modification_donnees', 'Modification de données'), ('rapport', 'Génération de rapport'), ('recherche_membre', 'Recherche de membre')], max_length=50, verbose_name="Type d'activité")),
                ('description', models.TextField(verbose_name='Description')),
                ('date_activite', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'activité")),
                ('donnees_concernees', models.JSONField(blank=True, default=dict, verbose_name='Données concernées')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': "Activité d'agent",
                'verbose_name_plural': 'Activités des agents',
                'ordering': ['-date_activite'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('poste', models.CharField(max_length=100, verbose_name='Poste occupé')),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('limite_bons_quotidienne', models.IntegerField(default=20, verbose_name='Limite quotidienne de bons')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email_professionnel', models.EmailField(blank=True, max_length=254, verbose_name='Email professionnel')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='BonSoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code du bon')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_expiration', models.DateTimeField(verbose_name="Date d'expiration")),
                ('date_utilisation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'utilisation")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('utilise', 'Utilisé'), ('expire', 'Expiré'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('montant_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant maximum')),
                ('montant_utilise', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant utilisé')),
                ('motif_consultation', models.TextField(verbose_name='Motif de consultation')),
                ('type_soin', models.CharField(max_length=100, verbose_name='Type de soin')),
                ('urgence', models.CharField(choices=[('normale', 'Normale'), ('urgente', 'Urgente'), ('critique', 'Critique')], default='normale', max_length=20, verbose_name="Niveau d'urgence")),
                ('etablissement_medical', models.CharField(blank=True, max_length=200, verbose_name='Établissement médical')),
                ('notes', models.TextField(blank=True, verbose_name='Notes complémentaires')),
            ],
            options={
                'verbose_name': 'Bon de soin',
                'verbose_name_plural': 'Bons de soin',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(verbose_name='Mois de performance')),
                ('bons_crees', models.IntegerField(default=0, verbose_name='Bons créés')),
                ('verifications_effectuees', models.IntegerField(default=0, verbose_name='Vérifications effectuées')),
                ('membres_contactes', models.IntegerField(default=0, verbose_name='Membres contactés')),
                ('recherches_effectuees', models.IntegerField(default=0, verbose_name='Recherches effectuées')),
                ('taux_validation', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de validation (%)')),
                ('satisfaction_membres', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Satisfaction membres (%)')),
                ('objectif_atteint', models.BooleanField(default=False, verbose_name='Objectif atteint')),
            ],
            options={
                'verbose_name': "Performance d'agent",
                'verbose_name_plural': 'Performances des agents',
                'ordering': ['-mois', 'agent'],
            },
        ),
        migrations.CreateModel(
            name='PermissionAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Permission d'agent",
                'verbose_name_plural': "Permissions d'agents",
                'ordering': ['module', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='RoleAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=dict)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Rôle d'agent",
                'verbose_name_plural': "Rôles d'agents",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_verification', models.DateTimeField(auto_now_add=True, verbose_name='Date de vérification')),
                ('statut_cotisation', models.CharField(choices=[('a_jour', 'À jour'), ('en_retard', 'En retard'), ('impayee', 'Impayée'), ('exoneree', 'Exonérée')], max_length=20, verbose_name='Statut de cotisation')),
                ('date_dernier_paiement', models.DateField(blank=True, null=True, verbose_name='Date du dernier paiement')),
                ('montant_dernier_paiement', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant du dernier paiement')),
                ('prochaine_echeance', models.DateField(verbose_name='Prochaine échéance')),
                ('jours_retard', models.IntegerField(default=0, verbose_name='Jours de retard')),
                ('montant_dette', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant dû')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('pieces_justificatives', models.FileField(blank=True, null=True, upload_to='verifications/cotisations/', verbose_name='Pièces justificatives')),
                ('notifier_membre', models.BooleanField(default=False, verbose_name='Membre notifié')),
            ],
            options={
                'verbose_name': 'Vérification de cotisation',
                'verbose_name_plural': 'Vérifications de cotisation',
                'ordering': ['-date_verification'],
            },
        ),
    ]
