# Generated by Django 5.2.7 on 2025-12-05 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('assureur', '0001_initial'),
        ('communication', '0001_initial'),
        ('medecin', '0001_initial'),
        ('membres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='assureur',
            field=models.ForeignKey(blank=True, help_text='Assureur pour lequel cet agent travaille', null=True, on_delete=django.db.models.deletion.CASCADE, to='assureur.assureur', verbose_name='Assureur associé'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='activiteagent',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent', verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='bonsoin',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent', verbose_name='Agent créateur'),
        ),
        migrations.AddField(
            model_name='bonsoin',
            name='medecin_destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecin.medecin', verbose_name='Médecin destinataire'),
        ),
        migrations.AddField(
            model_name='bonsoin',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membre', verbose_name='Membre bénéficiaire'),
        ),
        migrations.AddField(
            model_name='bonsoin',
            name='message_interne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.message', verbose_name='Message interne lié'),
        ),
        migrations.AddField(
            model_name='agent',
            name='bons_soin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_bons', to='agents.bonsoin'),
        ),
        migrations.AddField(
            model_name='performanceagent',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agents.agent', verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.roleagent', verbose_name='Rôle'),
        ),
        migrations.AddField(
            model_name='verificationcotisation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent', verbose_name='Agent vérificateur'),
        ),
        migrations.AddField(
            model_name='verificationcotisation',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membre', verbose_name='Membre vérifié'),
        ),
        migrations.AddField(
            model_name='agent',
            name='verification_cotisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_verifications', to='agents.verificationcotisation'),
        ),
        migrations.AddIndex(
            model_name='activiteagent',
            index=models.Index(fields=['agent', 'date_activite'], name='agents_acti_agent_i_209d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='activiteagent',
            index=models.Index(fields=['type_activite'], name='agents_acti_type_ac_4cbec1_idx'),
        ),
        migrations.AddIndex(
            model_name='bonsoin',
            index=models.Index(fields=['code'], name='agents_bons_code_006da4_idx'),
        ),
        migrations.AddIndex(
            model_name='bonsoin',
            index=models.Index(fields=['statut'], name='agents_bons_statut_0065bf_idx'),
        ),
        migrations.AddIndex(
            model_name='bonsoin',
            index=models.Index(fields=['date_creation'], name='agents_bons_date_cr_a91488_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performanceagent',
            unique_together={('agent', 'mois')},
        ),
        migrations.AddIndex(
            model_name='verificationcotisation',
            index=models.Index(fields=['membre', 'date_verification'], name='agents_veri_membre__453ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcotisation',
            index=models.Index(fields=['statut_cotisation'], name='agents_veri_statut__4a8578_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='verificationcotisation',
            unique_together={('agent', 'membre', 'date_verification')},
        ),
    ]
