# Generated by Django 5.2.7 on 2025-12-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='bons_soin',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='verification_cotisation',
        ),
        migrations.RemoveField(
            model_name='bonsoin',
            name='message_interne',
        ),
        migrations.AlterField(
            model_name='agent',
            name='date_embauche',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
    ]
