# Generated by Django 5.2.7 on 2025-12-05 07:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('prix_reference', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type de soin',
                'verbose_name_plural': 'Types de soins',
            },
        ),
        migrations.CreateModel(
            name='BonDeSoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_soin', models.DateField(default=django.utils.timezone.now)),
                ('symptomes', models.TextField(default='')),
                ('diagnostic', models.TextField(default='')),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='attente', max_length=20)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medecin', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Medecin'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membres.membre')),
            ],
            options={
                'verbose_name': 'Bon de soin',
                'verbose_name_plural': 'Bons de soin',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=200)),
                ('posologie', models.CharField(max_length=100)),
                ('duree', models.CharField(blank=True, max_length=100, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('termine', 'Terminé')], default='en_attente', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('bon_de_soin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='soins.bondesoin')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soin', models.DateTimeField(auto_now_add=True)),
                ('date_realisation', models.DateField()),
                ('diagnostic', models.TextField()),
                ('observations', models.TextField(blank=True)),
                ('duree_sejour', models.PositiveIntegerField(blank=True, default=0, help_text='Durée en jours', null=True)),
                ('cout_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cout_reel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taux_prise_charge', models.PositiveIntegerField(blank=True, default=80, help_text="Pourcentage pris en charge par l'assureur", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('termine', 'Terminé')], default='attente', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_crees', to=settings.AUTH_USER_MODEL)),
                ('medecin', models.ForeignKey(limit_choices_to={'groups__name': 'Medecin'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='membres.membre')),
                ('valide_par', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Assureur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_valides', to=settings.AUTH_USER_MODEL)),
                ('type_soin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soins.typesoin')),
            ],
            options={
                'verbose_name': 'Soin',
                'verbose_name_plural': 'Soins',
                'ordering': ['-date_realisation'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=200)),
                ('posologie', models.CharField(max_length=100)),
                ('duree_traitement', models.PositiveIntegerField(help_text='Durée en jours')),
                ('instructions', models.TextField(blank=True)),
                ('date_prescription', models.DateTimeField(auto_now_add=True)),
                ('soin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='soins.soin')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
            },
        ),
        migrations.CreateModel(
            name='DocumentSoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('ordonnance', 'Ordonnance'), ('resultat', "Résultat d'analyse"), ('compte_rendu', 'Compte-rendu'), ('facture', 'Facture'), ('autre', 'Autre')], max_length=20)),
                ('fichier', models.FileField(upload_to='documents/soins/')),
                ('nom', models.CharField(max_length=200)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('soin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='soins.soin')),
            ],
            options={
                'verbose_name': 'Document de soin',
                'verbose_name_plural': 'Documents de soin',
            },
        ),
    ]
