services:
  - type: web
    name: mutuelle-core
    env: python
    region: frankfurt
    plan: free
    
    # Tout dans une seule commande
    buildCommand: |
      chmod +x build_and_run.sh
      ./build_and_run.sh
    
    # Pas besoin de startCommand séparé si tout est dans buildCommand
    startCommand: gunicorn mutuelle_core.wsgi:application --bind 0.0.0.0:$PORT
    
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mutuelle_core.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"