services:
  - type: web
    name: mutuelle-core
    env: python
    region: frankfurt
    plan: free
    
    # Construction
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    
    # Démarrage - CRITIQUE : utiliser 'app:application'
    startCommand: gunicorn app:application
    
    # Variables d'environnement
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: "true"
      - key: DEBUG
        value: "false"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: SECRET_KEY
        generateValue: true
    
    autoDeploy: true