#!/bin/bash
echo "🚀 MISE À JOUR CONFIGURATION RAILWAY"
echo "===================================="
echo ""
echo "📋 AJOUTEZ CES VARIABLES DANS RAILWAY:"
echo ""
echo "RAILWAY=true"
echo "DEBUG=True"
echo "SECRET_KEY=$(openssl rand -hex 32)"
echo ""
echo "ALLOWED_HOSTS=web-production-555c.up.railway.app,*.railway.app,localhost,127.0.0.1"
echo ""
echo "CSRF_TRUSTED_ORIGINS=https://web-production-555c.up.railway.app,https://*.railway.app,http://web-production-555c.up.railway.app,http://*.railway.app"
echo ""
echo "CORS_ALLOWED_ORIGINS=https://web-production-555c.up.railway.app,https://*.railway.app"
echo ""
echo "RAILWAY_PUBLIC_DOMAIN=web-production-555c.up.railway.app"
echo ""
echo "DISABLE_COLLECTSTATIC=1"
echo ""
echo "===================================="
echo "📝 Instructions:"
echo "1. Allez dans Railway > Votre projet > Variables"
echo "2. Supprimez toutes les variables existantes"
echo "3. Ajoutez CHAQUE variable ci-dessus"
echo "4. Redéployez"
echo ""
echo "✅ Après déploiement, testez:"
echo "   ./test_login_final.sh"
