# Generated by Django 5.2.7 on 2025-12-05 07:17

import django.contrib.sessions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sessions.session',),
            managers=[
                ('objects', django.contrib.sessions.models.SessionManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type_document', models.CharField(choices=[('ORD', 'Ordonnance'), ('BON', 'Bon')], max_length=3)),
                ('document_id', models.PositiveIntegerField()),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'lu'], name='core_notifi_utilisa_8fbf66_idx'), models.Index(fields=['type_document', 'document_id'], name='core_notifi_type_do_335a63_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartageAutomatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('ORD', 'Ordonnance'), ('BON', 'Bon')], max_length=3)),
                ('document_id', models.PositiveIntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('visible_par', models.ManyToManyField(related_name='documents_visibles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['type_document', 'document_id'], name='core_partag_type_do_875366_idx')],
                'unique_together': {('type_document', 'document_id')},
            },
        ),
    ]
