# Generated by Django 5.2.7 on 2025-12-05 07:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assureur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du paiement')),
                ('mode_paiement', models.CharField(choices=[('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('MOBILE', 'Paiement mobile'), ('AUTRE', 'Autre')], default='VIREMENT', max_length=20, verbose_name='Mode de paiement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé'), ('ECHEC', 'Échec'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut du paiement')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Référence du paiement')),
                ('numero_transaction', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de transaction')),
                ('banque', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banque émettrice')),
                ('date_valeur', models.DateField(blank=True, null=True, verbose_name='Date de valeur')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes internes')),
                ('preuve_paiement', models.FileField(blank=True, null=True, upload_to='paiements/preuves/%Y/%m/', verbose_name='Preuve de paiement')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='assureur.bonpriseencharge', verbose_name='Bon de prise en charge')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('modifie_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='paiements.paiement')),
            ],
            options={
                'verbose_name': 'Historique de paiement',
                'verbose_name_plural': 'Historiques de paiements',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_rembourse', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant remboursé')),
                ('motif', models.TextField(verbose_name='Motif du remboursement')),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demandé'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('PAYEE', 'Payée')], default='DEMANDE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remboursement', to='paiements.paiement')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
            },
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut'], name='paiements_p_statut_b61122_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date_paiement'], name='paiements_p_date_pa_cc74b5_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['reference'], name='paiements_p_referen_a81c35_idx'),
        ),
    ]
