# Generated by Django 5.2.7 on 2025-12-05 07:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(max_length=20, unique=True, verbose_name='Numéro du bon')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_emission', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('type_soin', models.CharField(choices=[('CONSULT', '🩺 Consultation médicale'), ('MEDIC', '💊 Médicaments'), ('ANALYSE', '🧪 Analyses médicales'), ('RADIO', '📷 Radiologie'), ('HOSPIT', '🏥 Hospitalisation'), ('CHIRURGIE', '🔪 Chirurgie'), ('MATERIEL', '🩹 Matériel médical'), ('AUTRE', '📄 Autre')], max_length=15, verbose_name='Type de soin')),
                ('description', models.TextField(blank=True, verbose_name='Description des soins')),
                ('lieu_soins', models.CharField(blank=True, max_length=200, verbose_name='Lieu des soins')),
                ('date_soins', models.DateField(default=django.utils.timezone.now, verbose_name='Date des soins')),
                ('diagnostic', models.TextField(blank=True, verbose_name='Diagnostic')),
                ('numero_ordonnance', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'ordonnance")),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total')),
                ('taux_remboursement', models.DecimalField(decimal_places=2, default=80, max_digits=5, verbose_name='Taux de remboursement (%)')),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant remboursé')),
                ('frais_dossier', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Frais de dossier')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('REMBOURSE', 'Remboursé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=15)),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('motif_refus', models.TextField(blank=True, verbose_name='Motif de refus')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='bons/pieces_jointes/', verbose_name='Pièce jointe')),
                ('facture', models.FileField(blank=True, null=True, upload_to='bons/factures/', verbose_name='Facture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medecin_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_prescrits', to=settings.AUTH_USER_MODEL, verbose_name='Médecin traitant')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Bon de soins',
                'verbose_name_plural': 'Bons de soins',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneBon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire')),
                ('taux_remboursement', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Taux remboursement (%)')),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='membres.bon')),
            ],
            options={
                'verbose_name': 'Ligne de bon',
                'verbose_name_plural': 'Lignes de bon',
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_unique', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, default='', max_length=15)),
                ('numero_urgence', models.CharField(blank=True, default='', max_length=15)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_retard', 'En retard de paiement'), ('inactif', 'Inactif')], default='actif', max_length=20)),
                ('categorie', models.CharField(choices=[('standard', 'Standard'), ('femme_enceinte', 'Femme enceinte'), ('enfant', 'Enfant'), ('senior', 'Senior')], default='standard', max_length=20)),
                ('cmu_option', models.BooleanField(default=False)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('profession', models.CharField(blank=True, default='', max_length=100)),
                ('date_derniere_cotisation', models.DateField(blank=True, null=True)),
                ('prochain_paiement_le', models.DateField(blank=True, null=True)),
                ('est_femme_enceinte', models.BooleanField(default=False, verbose_name='Femme enceinte')),
                ('date_debut_grossesse', models.DateField(blank=True, null=True, verbose_name='Date début grossesse')),
                ('date_accouchement_prevue', models.DateField(blank=True, null=True, verbose_name='Date accouchement prévue')),
                ('date_accouchement_reelle', models.DateField(blank=True, null=True, verbose_name='Date accouchement réelle')),
                ('avance_payee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Avance payée (FCFA)')),
                ('carte_adhesion_payee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Carte adhésion payée (FCFA)')),
                ('taux_couverture', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de couverture (%)')),
                ('type_piece_identite', models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('PASSEPORT', 'Passeport'), ('PERMIS', 'Permis de Conduire'), ('CARTE_SEJOUR', 'Carte de Séjour')], default='CNI', max_length=20)),
                ('numero_piece_identite', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="Numéro de pièce d'identité")),
                ('piece_identite_recto', models.FileField(blank=True, help_text='Format: PDF, JPG, PNG (max 5MB)', null=True, upload_to='pieces_identite/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name="Recto de la pièce d'identité")),
                ('piece_identite_verso', models.FileField(blank=True, help_text='Format: PDF, JPG, PNG (max 5MB) - Optionnel pour certains documents', null=True, upload_to='pieces_identite/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name="Verso de la pièce d'identité")),
                ('photo_identite', models.ImageField(blank=True, help_text='Format: JPG, PNG (max 2MB) - Photo récente et claire', null=True, upload_to='photos_identite/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name="Photo d'identité")),
                ('date_expiration_piece', models.DateField(blank=True, null=True, verbose_name="Date d'expiration de la pièce")),
                ('statut_documents', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('EXPIRED', 'Expiré')], default='EN_ATTENTE', max_length=15)),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif de rejet des documents')),
                ('date_validation_documents', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation des documents')),
                ('score_risque', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Score de risque')),
                ('niveau_risque', models.CharField(choices=[('faible', '🟢 Faible risque'), ('modere', '🟡 Risque modéré'), ('eleve', '🟠 Risque élevé'), ('tres_eleve', '🔴 Risque très élevé')], default='faible', max_length=20)),
                ('fraude_suspectee', models.BooleanField(default=False, verbose_name='Fraude suspectée par IA')),
                ('date_dernier_score', models.DateTimeField(blank=True, null=True, verbose_name='Date du dernier calcul de score')),
                ('date_derniere_analyse_ia', models.DateTimeField(blank=True, null=True, verbose_name='Dernière analyse IA')),
                ('agent_createur', models.ForeignKey(blank=True, help_text='Agent qui a créé ce compte membre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent', verbose_name='Agent créateur')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membre', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueValidationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('ancien_statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('EXPIRED', 'Expiré')], max_length=15)),
                ('nouveau_statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('EXPIRED', 'Expiré')], max_length=15)),
                ('motif', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agent validateur')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_documents', to='membres.membre')),
            ],
            options={
                'verbose_name': 'Historique validation document',
                'verbose_name_plural': 'Historiques validation documents',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_echeance', models.DateField()),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('PAYEE', 'Payée'), ('EN_RETARD', 'En retard'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='membres.membre')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-date_echeance'],
            },
        ),
        migrations.AddField(
            model_name='bon',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membre', verbose_name='Membre bénéficiaire'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEMBRE', 'Membre'), ('MEDECIN', 'Médecin'), ('ASSUREUR', 'Assureur'), ('AGENT', 'Agent'), ('ADMIN', 'Administrateur')], default='MEMBRE', max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='UserLoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_login_sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['numero_unique'], name='membres_mem_numero__3a8d66_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['nom', 'prenom'], name='membres_mem_nom_849d64_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['statut'], name='membres_mem_statut_b54dde_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['date_inscription'], name='membres_mem_date_in_f60ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['statut_documents'], name='membres_mem_statut__d3a2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='bon',
            index=models.Index(fields=['numero_bon'], name='membres_bon_numero__88c591_idx'),
        ),
        migrations.AddIndex(
            model_name='bon',
            index=models.Index(fields=['membre'], name='membres_bon_membre__599530_idx'),
        ),
        migrations.AddIndex(
            model_name='bon',
            index=models.Index(fields=['statut'], name='membres_bon_statut_26f266_idx'),
        ),
        migrations.AddIndex(
            model_name='bon',
            index=models.Index(fields=['date_soins'], name='membres_bon_date_so_4c3837_idx'),
        ),
        migrations.AddIndex(
            model_name='bon',
            index=models.Index(fields=['medecin_traitant'], name='membres_bon_medecin_09ba2f_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginsession',
            index=models.Index(fields=['user', 'login_time'], name='user_login__user_id_4afcfb_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginsession',
            index=models.Index(fields=['login_time'], name='user_login__login_t_538932_idx'),
        ),
    ]
