# Generated by Django 5.2.7 on 2025-12-05 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentPublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('principe_actif', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('forme_galenique', models.CharField(max_length=100)),
                ('laboratoire', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('generique', 'Générique'), ('princeps', 'Princeps'), ('OTC', 'Médicament en vente libre'), ('ordonnance', 'Sur ordonnance')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField(default=0)),
                ('necessite_ordonnance', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Médicament public',
                'verbose_name_plural': 'Médicaments publics',
            },
        ),
        migrations.CreateModel(
            name='CommandePublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_preparation', 'En préparation'), ('pret', 'Prête à être retirée'), ('retiree', 'Retirée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_retrait_prevu', models.DateTimeField(blank=True, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_pharmacie_public', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande publique',
                'verbose_name_plural': 'Commandes publiques',
            },
        ),
        migrations.CreateModel(
            name='LigneCommandePublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=8)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacie_public.commandepublic')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie_public.medicamentpublic')),
            ],
            options={
                'verbose_name': 'Ligne de commande publique',
                'verbose_name_plural': 'Lignes de commande publiques',
            },
        ),
        migrations.CreateModel(
            name='PharmaciePublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pharmacie', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('type_pharmacie', models.CharField(choices=[('officine', 'Officine'), ('hospitaliere', 'Hospitalière'), ('parapharmacie', 'Parapharmacie')], default='officine', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('actif', 'Actif'), ('inactif', 'Inactif'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('horaires_ouverture', models.TextField(default='Lun-Ven: 08:00-19:00, Sam: 08:00-12:00')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('est_de_garde', models.BooleanField(default=False)),
                ('prochaine_garde', models.DateTimeField(blank=True, null=True)),
                ('partenaire_mutuelle', models.BooleanField(default=False)),
                ('numero_agrement', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacie publique',
                'verbose_name_plural': 'Pharmacies publiques',
            },
        ),
        migrations.AddField(
            model_name='medicamentpublic',
            name='pharmacie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='pharmacie_public.pharmaciepublic'),
        ),
        migrations.CreateModel(
            name='GardePublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('type_garde', models.CharField(choices=[('nuit', 'Garde de nuit'), ('weekend', 'Garde de weekend'), ('jour_ferie', 'Jour férié')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie_public.pharmaciepublic')),
            ],
            options={
                'verbose_name': 'Garde publique',
                'verbose_name_plural': 'Gardes publiques',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='commandepublic',
            name='pharmacie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='pharmacie_public.pharmaciepublic'),
        ),
    ]
