# Generated by Django 5.2.7 on 2025-12-05 07:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('type_modele', models.CharField(choices=[('detection_fraude', 'Détection de fraude'), ('scoring_risque', 'Scoring de risque'), ('prediction_retard', 'Prédiction de retard')], max_length=50)),
                ('fichier_modele', models.FileField(blank=True, null=True, upload_to='modeles_ia/')),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_entrainement', models.DateTimeField(default=django.utils.timezone.now)),
                ('est_actif', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Modèle IA',
                'verbose_name_plural': 'Modèles IA',
            },
        ),
        migrations.CreateModel(
            name='AnalyseIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyse', models.CharField(max_length=50)),
                ('score_confiance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('resultat', models.JSONField(default=dict)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membre')),
                ('verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.verificationcotisation')),
            ],
            options={
                'verbose_name': 'Analyse IA',
                'verbose_name_plural': 'Analyses IA',
                'ordering': ['-date_analyse'],
            },
        ),
    ]
