# Generated by Django 5.2.7 on 2025-12-05 07:17

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_assureur', models.CharField(default='Notre Assureur', max_length=200)),
                ('taux_couverture_defaut', models.DecimalField(decimal_places=2, default=80.0, max_digits=5, verbose_name='Taux de couverture par défaut (%)')),
                ('delai_validite_bon', models.IntegerField(default=30, verbose_name='Délai de validité des bons (jours)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration assurance',
                'verbose_name_plural': 'Configurations assurance',
            },
        ),
        migrations.CreateModel(
            name='StatistiquesAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=10, unique=True, verbose_name='Période (YYYY-MM)')),
                ('total_membres', models.IntegerField(default=0)),
                ('nouveaux_membres', models.IntegerField(default=0)),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_remboursements', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistique assurance',
                'verbose_name_plural': 'Statistiques assurance',
                'ordering': ['-periode'],
            },
        ),
        migrations.CreateModel(
            name='Assureur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_employe', models.CharField(max_length=20, unique=True)),
                ('departement', models.CharField(choices=[('gestion', 'Gestion des membres'), ('claims', 'Traitement des réclamations'), ('paiements', 'Service des paiements'), ('admin', 'Administration')], max_length=100)),
                ('date_embauche', models.DateField(default=datetime.date.today)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assureur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assureur',
                'verbose_name_plural': 'Assureurs',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Bon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(max_length=50, unique=True, verbose_name='Numéro de bon')),
                ('type_soin', models.CharField(choices=[('consultation', 'Consultation médicale'), ('analyse', 'Analyse médicale'), ('imagerie', 'Imagerie médicale'), ('hospitalisation', 'Hospitalisation'), ('pharmacie', 'Pharmacie'), ('dentaire', 'Soins dentaires'), ('optique', 'Soins optiques'), ('autre', 'Autre')], max_length=50, verbose_name='Type de soin')),
                ('description', models.TextField(blank=True, verbose_name='Description des soins')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('montant_prise_charge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant pris en charge')),
                ('montant_restant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant restant à charge')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateField()),
                ('date_soin', models.DateField(verbose_name='Date des soins')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('utilise', 'Utilisé'), ('expire', 'Expiré')], default='en_attente', max_length=20)),
                ('nom_medecin', models.CharField(max_length=200, verbose_name='Nom du médecin/établissement')),
                ('specialite', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_crees_assureur', to=settings.AUTH_USER_MODEL)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_assureur', to='membres.membre', verbose_name='Membre')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_valides_assureur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bon de prise en charge',
                'verbose_name_plural': 'Bons de prise en charge',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='BonDeSoin',
            fields=[
            ],
            options={
                'verbose_name': 'Bon de soin',
                'verbose_name_plural': 'Bons de soin',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assureur.bon',),
        ),
        migrations.CreateModel(
            name='BonPriseEnCharge',
            fields=[
            ],
            options={
                'verbose_name': 'Bon de prise en charge',
                'verbose_name_plural': 'Bons de prise en charge',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assureur.bon',),
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=7, verbose_name='Période (YYYY-MM)')),
                ('type_cotisation', models.CharField(choices=[('normale', 'Cotisation normale - 5000 FCFA'), ('femme_enceinte', 'Cotisation femme enceinte - 7500 FCFA')], default='normale', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant de la cotisation (FCFA)')),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('statut', models.CharField(choices=[('due', 'Due'), ('payee', 'Payée'), ('en_retard', 'En retard'), ('annulee', 'Annulée')], default='due', max_length=20)),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotisations_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name="Enregistré par l'assureur")),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations_assureur', to='membres.membre', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-periode', 'membre'],
            },
        ),
        migrations.CreateModel(
            name='RapportAssureur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_rapport', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel'), ('SPECIAL', 'Spécial')], max_length=50)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('nombre_bons_emis', models.IntegerField(default=0)),
                ('nombre_bons_utilises', models.IntegerField(default=0)),
                ('montant_total_emis', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_total_rembourse', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('assureur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_assureur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport Assureur',
                'verbose_name_plural': 'Rapports Assureurs',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_soin', models.CharField(max_length=100, verbose_name='Type de soin')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('montant_facture', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant facturé')),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant remboursé')),
                ('date_soin', models.DateField(verbose_name='Date des soins')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('en_cours', 'En cours de traitement'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('paye', 'Payé')], default='soumis', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='assureur.bon')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assureur_soins_soumis', to=settings.AUTH_USER_MODEL)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins_assureur', to='membres.membre')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assureur_soins_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soin',
                'verbose_name_plural': 'Soins',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence paiement')),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('mobile', 'Paiement mobile')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('initie', 'Initié'), ('valide', 'Validé'), ('annule', 'Annulé'), ('echec', 'Échec'), ('rembourse', 'Remboursé')], default='initie', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assureur_paiements_crees', to=settings.AUTH_USER_MODEL)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_assureur', to='membres.membre')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assureur_paiements_valides', to=settings.AUTH_USER_MODEL)),
                ('soin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='assureur.soin')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.AddIndex(
            model_name='bon',
            index=models.Index(fields=['numero_bon'], name='assureur_bo_numero__b0f16f_idx'),
        ),
        migrations.AddIndex(
            model_name='bon',
            index=models.Index(fields=['membre', 'statut'], name='assureur_bo_membre__113941_idx'),
        ),
        migrations.AddIndex(
            model_name='bon',
            index=models.Index(fields=['date_soin'], name='assureur_bo_date_so_f84c02_idx'),
        ),
        migrations.AddIndex(
            model_name='bon',
            index=models.Index(fields=['statut'], name='assureur_bo_statut_22c1e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cotisation',
            unique_together={('membre', 'periode')},
        ),
    ]
