# Generated by Django 5.2.7 on 2025-12-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assureur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('espece', 'Espèces'), ('carte', 'Carte bancaire'), ('mobile_money', 'Paiement mobile'), ('autre', 'Autre')], max_length=20),
        ),
    ]
