# Generated by Django 5.2.7 on 2025-12-05 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='GroupeCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du groupe')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_groupe', models.CharField(choices=[('EQUIPE', 'Équipe de travail'), ('SERVICE', 'Service/Département'), ('PROJET', 'Projet spécifique'), ('GENERAL', 'Général')], default='EQUIPE', max_length=20, verbose_name='Type de groupe')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Groupe actif')),
                ('est_public', models.BooleanField(default=False, verbose_name='Groupe public')),
                ('code_acces', models.CharField(blank=True, max_length=50, verbose_name="Code d'accès")),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('membres', models.ManyToManyField(related_name='groupes_communication', to=settings.AUTH_USER_MODEL, verbose_name='Membres')),
            ],
            options={
                'verbose_name': 'Groupe de communication',
                'verbose_name_plural': 'Groupes de communication',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('contenu', models.TextField()),
                ('type_message', models.CharField(choices=[('NOTIFICATION', 'Notification'), ('ALERTE', 'Alerte'), ('MESSAGE', 'Message'), ('BON_SOIN', 'Bon de Soin'), ('DOCUMENT', 'Document')], default='MESSAGE', max_length=20)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.conversation')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('INFO', 'Information'), ('ALERTE', 'Alerte'), ('SUCCES', 'Succès'), ('ERREUR', 'Erreur'), ('BON_SOIN', 'Bon de Soin'), ('RDV', 'Rendez-vous'), ('PAIEMENT', 'Paiement')], default='INFO', max_length=50)),
                ('est_lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='pieces_jointes/%Y/%m/%d/')),
                ('nom_original', models.CharField(max_length=255)),
                ('type_fichier', models.CharField(choices=[('PDF', 'Document PDF'), ('IMAGE', 'Image'), ('DOCUMENT', 'Document Word/Excel'), ('AUTRE', 'Autre type')], default='AUTRE', max_length=20)),
                ('taille', models.BigIntegerField(default=0, help_text='Taille en octets')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('est_valide', models.BooleanField(default=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='communication.message')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='MessageGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('type_message', models.CharField(choices=[('NOTIFICATION', 'Notification'), ('ALERTE', 'Alerte'), ('MESSAGE', 'Message'), ('BON_SOIN', 'Bon de Soin'), ('DOCUMENT', 'Document')], default='MESSAGE', max_length=20, verbose_name='Type de message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('est_important', models.BooleanField(default=False, verbose_name='Message important')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_groupe_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.groupecommunication', verbose_name='Groupe')),
                ('pieces_jointes', models.ManyToManyField(blank=True, related_name='messages_groupe', to='communication.piecejointe', verbose_name='Pièces jointes')),
            ],
            options={
                'verbose_name': 'Message de groupe',
                'verbose_name_plural': 'Messages de groupe',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.AddIndex(
            model_name='groupecommunication',
            index=models.Index(fields=['nom'], name='communicati_nom_3b7262_idx'),
        ),
        migrations.AddIndex(
            model_name='groupecommunication',
            index=models.Index(fields=['type_groupe'], name='communicati_type_gr_ea4060_idx'),
        ),
        migrations.AddIndex(
            model_name='groupecommunication',
            index=models.Index(fields=['est_actif'], name='communicati_est_act_9a9c81_idx'),
        ),
        migrations.AddIndex(
            model_name='messagegroupe',
            index=models.Index(fields=['groupe', 'date_envoi'], name='communicati_groupe__025619_idx'),
        ),
        migrations.AddIndex(
            model_name='messagegroupe',
            index=models.Index(fields=['expediteur', 'date_envoi'], name='communicati_expedit_76d0c6_idx'),
        ),
    ]
