# Generated by Django 5.2.7 on 2025-12-05 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assureur', '0001_initial'),
        ('medecin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du médicament')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='OrdonnancePharmacien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament_delivre', models.CharField(max_length=255, verbose_name='Médicament délivré')),
                ('posologie_appliquee', models.TextField(verbose_name='Posologie appliquée')),
                ('duree_traitement', models.PositiveIntegerField(default=7, verbose_name='Durée du traitement (jours)')),
                ('instructions_supplementaires', models.TextField(blank=True, verbose_name='Instructions supplémentaires')),
                ('date_reception', models.DateTimeField(auto_now_add=True, verbose_name='Date de réception')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_preparation', models.DateTimeField(blank=True, null=True, verbose_name='Date de préparation')),
                ('date_service', models.DateTimeField(blank=True, null=True, verbose_name='Date de service')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('PREPAREE', 'Préparée'), ('SERVIE', 'Servie'), ('ANNULEE', 'Annulée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('notes_pharmacien', models.TextField(blank=True, verbose_name='Notes du pharmacien')),
                ('observations_service', models.TextField(blank=True, verbose_name='Observations lors du service')),
                ('quantite_delivree', models.PositiveIntegerField(default=1, verbose_name='Quantité délivrée')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix unitaire')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant total')),
                ('taux_remboursement', models.DecimalField(decimal_places=2, default=0.7, max_digits=5, verbose_name='Taux de remboursement')),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant remboursé')),
                ('bon_prise_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances_pharmacien', to='assureur.bon', verbose_name='Bon de prise en charge')),
                ('ordonnance_medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestion_pharmacien', to='medecin.ordonnance', verbose_name='Ordonnance du médecin')),
                ('pharmacien_validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnances_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordonnance Pharmacien',
                'verbose_name_plural': 'Ordonnances Pharmacien',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('VALIDATION', 'Validation ordonnance'), ('PREPARATION', 'Préparation ordonnance'), ('SERVICE', 'Service ordonnance'), ('ANNULATION', 'Annulation ordonnance'), ('MODIFICATION', 'Modification ordonnance'), ('CONSULTATION', 'Consultation ordonnance')], max_length=20, verbose_name="Type d'action")),
                ('details_action', models.TextField(verbose_name="Détails de l'action")),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('ancien_statut', models.CharField(blank=True, max_length=20, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(blank=True, max_length=20, verbose_name='Nouveau statut')),
                ('pharmacien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pharmacien')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_services', to='pharmacien.ordonnancepharmacien')),
            ],
            options={
                'verbose_name': 'Historique Service',
                'verbose_name_plural': 'Historiques Services',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pharmacie', models.CharField(max_length=255, verbose_name='Nom de la pharmacie')),
                ('adresse_pharmacie', models.TextField(verbose_name='Adresse de la pharmacie')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('actif', models.BooleanField(default=True, verbose_name='Pharmacie active')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('numero_pharmacien', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro de pharmacien')),
                ('specialite', models.CharField(blank=True, max_length=100, verbose_name='Spécialité')),
                ('horaires_ouverture', models.TextField(blank=True, verbose_name="Horaires d'ouverture")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacien',
                'verbose_name_plural': 'Pharmaciens',
                'ordering': ['nom_pharmacie'],
            },
        ),
        migrations.CreateModel(
            name='StockPharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medicament', models.CharField(max_length=255, verbose_name='Nom du médicament')),
                ('code_medicament', models.CharField(blank=True, max_length=100, verbose_name='Code du médicament')),
                ('categorie', models.CharField(choices=[('ANTIBIOTIQUE', 'Antibiotique'), ('ANALGESIQUE', 'Analgésique'), ('ANTI_INFLAMMATOIRE', 'Anti-inflammatoire'), ('VITAMINE', 'Vitamine'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50, verbose_name='Catégorie')),
                ('quantite_stock', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('seuil_alerte', models.PositiveIntegerField(default=10, verbose_name="Seuil d'alerte")),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat")),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('date_peremption', models.DateField(blank=True, null=True, verbose_name='Date de péremption')),
                ('actif', models.BooleanField(default=True, verbose_name='Médicament actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='pharmacien.pharmacien')),
            ],
            options={
                'verbose_name': 'Stock Pharmacie',
                'verbose_name_plural': 'Stocks Pharmacie',
                'ordering': ['nom_medicament'],
            },
        ),
        migrations.AddIndex(
            model_name='ordonnancepharmacien',
            index=models.Index(fields=['statut'], name='pharmacien__statut_5089ad_idx'),
        ),
        migrations.AddIndex(
            model_name='ordonnancepharmacien',
            index=models.Index(fields=['date_reception'], name='pharmacien__date_re_c54073_idx'),
        ),
        migrations.AddIndex(
            model_name='ordonnancepharmacien',
            index=models.Index(fields=['ordonnance_medecin'], name='pharmacien__ordonna_c060c5_idx'),
        ),
        migrations.AddIndex(
            model_name='ordonnancepharmacien',
            index=models.Index(fields=['pharmacien_validateur'], name='pharmacien__pharmac_facf3d_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueservice',
            index=models.Index(fields=['ordonnance', 'date_action'], name='pharmacien__ordonna_1fabf3_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueservice',
            index=models.Index(fields=['pharmacien', 'date_action'], name='pharmacien__pharmac_e28227_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueservice',
            index=models.Index(fields=['type_action'], name='pharmacien__type_ac_30d407_idx'),
        ),
        migrations.AddIndex(
            model_name='stockpharmacie',
            index=models.Index(fields=['pharmacie', 'actif'], name='pharmacien__pharmac_299065_idx'),
        ),
        migrations.AddIndex(
            model_name='stockpharmacie',
            index=models.Index(fields=['quantite_stock'], name='pharmacien__quantit_77d052_idx'),
        ),
        migrations.AddIndex(
            model_name='stockpharmacie',
            index=models.Index(fields=['date_peremption'], name='pharmacien__date_pe_b52df1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockpharmacie',
            index=models.Index(fields=['categorie'], name='pharmacien__categor_d2351d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockpharmacie',
            unique_together={('pharmacie', 'nom_medicament', 'code_medicament')},
        ),
    ]
