# Generated by Django 5.2.7 on 2025-12-05 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegleScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('critere', models.CharField(max_length=200)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=4)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Règle Scoring',
                'verbose_name_plural': 'Règles Scoring',
                'ordering': ['-poids'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('niveau_risque', models.CharField(max_length=20)),
                ('details_calcul', models.JSONField(default=dict)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membre')),
            ],
            options={
                'verbose_name': 'Historique Score',
                'verbose_name_plural': 'Historiques Scores',
                'ordering': ['-date_calcul'],
            },
        ),
    ]
