# Generated by Django 5.2.7 on 2025-12-05 07:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateRelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_relance', models.CharField(choices=[('premier_rappel', 'Premier rappel'), ('relance_urgente', 'Relance urgente'), ('suspension_imminente', 'Suspension imminente')], max_length=50)),
                ('sujet', models.CharField(max_length=200)),
                ('template_html', models.TextField()),
                ('template_texte', models.TextField()),
                ('delai_jours', models.IntegerField(default=7)),
            ],
            options={
                'verbose_name': 'Template Relance',
                'verbose_name_plural': 'Templates Relance',
            },
        ),
        migrations.CreateModel(
            name='RelanceProgrammee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_programmation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('envoyee', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('programmee', 'Programmée'), ('envoyee', 'Envoyée'), ('erreur', 'Erreur'), ('annulee', 'Annulée')], default='programmee', max_length=20)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membre')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relances.templaterelance')),
            ],
            options={
                'verbose_name': 'Relance Programmee',
                'verbose_name_plural': 'Relances Programmees',
                'ordering': ['-date_programmation'],
            },
        ),
    ]
