# Generated by Django 5.2.7 on 2025-12-05 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_actif', models.BooleanField(default=True)),
                ('push_actif', models.BooleanField(default=True)),
                ('sms_actif', models.BooleanField(default=False)),
                ('notifications_systeme', models.BooleanField(default=True)),
                ('notifications_soins', models.BooleanField(default=True)),
                ('notifications_paiements', models.BooleanField(default=True)),
                ('notifications_alertes', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('INFO', 'Information'), ('ALERT', 'Alerte'), ('SUCCESS', 'Succès'), ('WARNING', 'Avertissement'), ('SYSTEM', 'Système')], default='INFO', max_length=10)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lu', models.DateTimeField(blank=True, null=True)),
                ('lien', models.URLField(blank=True, null=True)),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['user', 'lu'], name='notificatio_user_id_cf0127_idx'), models.Index(fields=['date_creation'], name='notificatio_date_cr_1b0271_idx'), models.Index(fields=['type_notification'], name='notificatio_type_no_ba8ea8_idx')],
            },
        ),
    ]
